# deploy.yml
name: deploy blog to dockerhub
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
      # 下载 git submodule
      #       - uses: srt32/git-actions@v0.0.3
      #         with:
      #           args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # npm install
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
        env:
          CI: true
      # build
      - name: hexo build
        run: |
          hexo clean
          hexo generate
        env:
          CI: true
      # 发布
      - uses: actions/checkout@v2 # pull代码到运行服务器上
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
        with:
          login-server: registry.cn-shenzhen.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
          region-id: cn-shenzhen # 务必正确填写镜像容器服务的登录地址
          username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
          password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
        run: |
          docker build -t registry.cn-shenzhen.aliyuncs.com/maya1900/my-site:$IMAGE_TAG .
          docker push registry.cn-shenzhen.aliyuncs.com/maya1900/my-site:$IMAGE_TAG

