# deploy.yml
name: deploy blog to aliyun
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
      # 下载 git submodule
      #       - uses: srt32/git-actions@v0.0.3
      #         with:
      #           args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # npm install
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
        env:
          CI: true
      # build
      - name: hexo build
        run: |
          hexo clean
          hexo generate
        env:
          CI: true
      # 发布
      - name: docker build
        uses: docker://alpine:3.8
        run: |
          echo  ${{DOCKER_PASSWORD}} | docker login -u ${{DOCKER_USERNAME}} --password-stdin
          docker build -t maya1900/may-blog:latest .
          docker push maya1900/may-blog:latest

#       # Deploy
#       - name: Deploy
#         uses: easingthemes/ssh-deploy@v2.0.7
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
#           ARGS: "-avz --delete"
#           SOURCE: "public/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.TARGET }}

