name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 10.x # 配置Node环境
      uses: actions/setup-node@v2 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "14"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'maya1900' # 换成你自己的邮箱和名字
        git config --global user.email '569760498@qq.com'
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        # npm i -g @cloudbase/cli ## 安装腾讯云部署
        npm install --save hexo-deployer-git
        npm i
  
    - name: Deploy
      run: |
        # publish
        hexo clean && hexo generate && hexo deploy # 执行部署程序
        # cloudbase hosting deploy . -e 'maya1900-1gfl7znh88ba4c68'
